### ISSUE TITLE
clang error prevents build

### ISSUE THREAD

**Issue by PaulCapestany** [mkrautz/objc#2]
I'm getting the following error when I try to install:

```
# github.com/mkrautz/variadic
clang: error: argument unused during compilation: '-fno-eliminate-unused-debug-types'
```

I'm running Go 1.1 and Xcode 5, so I've got Apple LLVM version 5.0 (clang-500.1.58) (based on LLVM 3.3svn)..

**Comment by mkrautz** [comment]
Hi @PaulCapestany,

I haven't yet installed Xcode 5, but it seems to me that with the removal of LLVM GCC from Xcode, 'gcc' now points directly to clang.

That's why you're seeing this error.  Cgo is trying to build with GCC flags using clang.

Can you please check if this works for you?

CC=clang go build

**Comment by PaulCapestany** [comment]
Yup, that worked — thanks!
